mem-agent-srv: Update the ttrpc to 0.8.4 to fix EOPNOTSUPP issue
Got:
Apr 09 08:34:30.590 INFO psi is available at "/sys/fs/cgroup/sys-fs-fuse-connections.mount"
 Apr 09 08:34:30.590 INFO psi is available at "/sys/fs/cgroup/sys-fs-fuse-connections.mount"
Apr 09 08:34:30.590 INFO MemAgent started
 Apr 09 08:34:30.591 INFO mem-agent start
 Apr 09 08:34:30.591 INFO mem_agent_loop wait timeout 18446744073709551615.999999999s
 Apr 09 08:34:30.591 INFO agent work thread start
 Apr 09 08:34:30.591 INFO memcg.work start
Apr 09 08:34:30.594 ERRO rpc::rpc_loop fail: Server::new().bind unix:///var/run/mem-agent.sock fail: Nix error: EOPNOTSUPP: Operation not supported on transport endpoint
Error: rpc::rpc_loop fail: Server::new().bind unix:///var/run/mem-agent.sock fail: Nix error: EOPNOTSUPP: Operation not supported on transport endpoint

This cause of this issue is 0.8.2 and 0.8.3 have a bug.

Update the ttrpc to 0.8.4 to fix this issue.

Fixes: #2

Signed-off-by: teawater <zhuhui@kylinos.cn>