srv.c: Fix logger issue
Got following with rust 1.85.1:
thread 'main' panicked at /home/teawater/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slog-scope-4.4.0/lib.rs:125:13:
slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
teawater@teawater-ThinkBook-16p-G5-IRX:~/mem-agent/example/target/x86_64-unknown-linux-musl/debug/examples$ sudo RUST_BACKTRACE=full ./mem-agent-srv

thread 'main' panicked at /home/teawater/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slog-scope-4.4.0/lib.rs:125:13:
slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.
stack backtrace:
   0:     0x79ab6343eb7a - std::backtrace_rs::backtrace::libunwind::trace::hac1c471b5851120d
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x79ab6343eb7a - std::backtrace_rs::backtrace::trace_unsynchronized::hc9a962aa3cdb9fc9
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x79ab6343eb7a - std::sys::backtrace::_print_fmt::h45aad34a09d776e0
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/sys/backtrace.rs:66:9
   3:     0x79ab6343eb7a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h4e0d2dcf301640a6
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/sys/backtrace.rs:39:26
   4:     0x79ab6347e5c3 - core::fmt::rt::Argument::fmt::h092a10b118c8fb5b
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/fmt/rt.rs:177:76
   5:     0x79ab6347e5c3 - core::fmt::write::hfbb439400fe59c82
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/fmt/mod.rs:1440:21
   6:     0x79ab6343b2b3 - std::io::Write::write_fmt::h30cec2808f3aa865
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/io/mod.rs:1887:15
   7:     0x79ab6343e9c2 - std::sys::backtrace::BacktraceLock::print::h57c17ebf44eb2fde
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/sys/backtrace.rs:42:9
   8:     0x79ab6343fa30 - std::panicking::default_hook::{{closure}}::h67f006365c532d55
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:295:22
   9:     0x79ab6343f810 - std::panicking::default_hook::hdda060f1a922d32c
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:322:9
  10:     0x79ab63440192 - std::panicking::rust_panic_with_hook::hb7cb7059bafe62da
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:828:13
  11:     0x79ab6344006c - std::panicking::begin_panic::{{closure}}::h2430d6d0c72d8b16
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:765:9
  12:     0x79ab6343f089 - std::sys::backtrace::__rust_end_short_backtrace::hfd1f269df375d97a
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/sys/backtrace.rs:168:18
  13:     0x79ab63060e10 - std::panicking::begin_panic::hcb2bb848463a7446
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:764:5
  14:     0x79ab633d986e - <slog_scope::NoGlobalLoggerSet as slog::Drain>::log::h4024c995a4e25e7c
                               at /home/teawater/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slog-scope-4.4.0/lib.rs:125:13
  15:     0x79ab631776c4 - <alloc::sync::Arc<D> as slog::Drain>::log::h6ddf3e955f26a932
                               at /home/teawater/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slog-2.7.0/src/lib.rs:1719:9
  16:     0x79ab6316e57b - slog::Logger<D>::log::h958c76f65f0bbe07
                               at /home/teawater/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/slog-2.7.0/src/lib.rs:1233:17
  17:     0x79ab631b1d60 - mem_agent::psi::check::h2fe708e15cee0708
                               at /home/teawater/mem-agent/src/misc.rs:26:9
  18:     0x79ab631a7de1 - mem_agent::memcg::MemCG::new::he48603fd28709a09
                               at /home/teawater/mem-agent/src/memcg.rs:459:13
  19:     0x79ab6317cb83 - mem_agent::agent::MemAgent::new::h462a18b6bc2d08a1
                               at /home/teawater/mem-agent/src/agent.rs:222:18
  20:     0x79ab630756e9 - mem_agent_srv::main::h99577977d5818ebf
                               at /home/teawater/mem-agent/example/srv.rs:83:21
  21:     0x79ab630c4b7b - core::ops::function::FnOnce::call_once::hd1a8b8c857d5ac91
                               at /home/teawater/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  22:     0x79ab6307ac2d - std::sys::backtrace::__rust_begin_short_backtrace::h4c089c871ea5480a
                               at /home/teawater/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  23:     0x79ab630d3dd1 - std::rt::lang_start::{{closure}}::h74f5072691ddc61b
                               at /home/teawater/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:195:18
  24:     0x79ab634339c7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h58740f8614d8ce92
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/ops/function.rs:284:13
  25:     0x79ab634339c7 - std::panicking::try::do_call::h8b55798bd0067ce5
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:584:40
  26:     0x79ab634339c7 - std::panicking::try::h90f23e7765a990e8
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:547:19
  27:     0x79ab634339c7 - std::panic::catch_unwind::h4a287629e0324d5c
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panic.rs:358:14
  28:     0x79ab634339c7 - std::rt::lang_start_internal::{{closure}}::ha07d5300ac9481a6
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/rt.rs:174:48
  29:     0x79ab634339c7 - std::panicking::try::do_call::h38e20208b4bbe60b
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:584:40
  30:     0x79ab634339c7 - std::panicking::try::h6097ac1bf9d693ea
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:547:19
  31:     0x79ab634339c7 - std::panic::catch_unwind::ha3bdd4ac9ef39400
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panic.rs:358:14
  32:     0x79ab634339c7 - std::rt::lang_start_internal::hc4326cb7d1702276
                               at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/rt.rs:174:20
  33:     0x79ab630d3daa - std::rt::lang_start::h3e7ff08ac26bce99
                               at /home/teawater/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:194:17
  34:     0x79ab6307646e - main

The cause of this issue is store the logger guard to _.  It is released
at once.
Change _ to _logger_guard to handle this issue.

Fixes: #1

Signed-off-by: teawater <zhuhui@kylinos.cn>