cgroup.rs: Fix build issue with musl
Got build issue with musl:
cargo build --target x86_64-unknown-linux-musl
   Compiling ttrpc-codegen v0.5.0
   Compiling ttrpc v0.8.4
   Compiling mem-agent-lib v0.2.0 (/home/teawater/mem-agent/crates/mem-agent-lib)
error[E0432]: unresolved import `nix::sys::statfs::CGROUP2_SUPER_MAGIC`
   --> crates/mem-agent-lib/src/cgroup.rs:6:32
    |
6   | use nix::sys::statfs::{statfs, CGROUP2_SUPER_MAGIC};
    |                                ^^^^^^^^^^^^^^^^^^^ no `CGROUP2_SUPER_MAGIC` in `sys::statfs`
    |
note: found an item that was configured out
   --> /home/teawater/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.23.2/src/sys/statfs.rs:134:11
    |
134 | pub const CGROUP2_SUPER_MAGIC: FsType = FsType(libc::CGROUP2_SUPER_MAGIC as fs_type_t);
    |           ^^^^^^^^^^^^^^^^^^^;
The cause is that CGROUP2_SUPER_MAGIC is defined with not musl:
pub const CGROUP2_SUPER_MAGIC: FsType = FsType(libc::CGROUP2_SUPER_MAGIC as fs_type_t);

Add a special musl CGROUP2_SUPER_MAGIC to handle this issue.

Signed-off-by: teawater <zhuhui@kylinos.cn>